In [4]:
import numpy as np

In [10]:
a=np.array(np.arange(1,20))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
difff=np.diff(a)/a[:-1]
difff

array([ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ,
        0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ,
        0.09090909,  0.08333333,  0.07692308,  0.07142857,  0.06666667,
        0.0625    ,  0.05882353,  0.05555556])

In [1]:
import numpy as np
import datetime

days=["Thursday","Friday","Monday","Tuesday","Wednesday","Thursday","Friday","Monday","Tuesday","Wednesday","Thursday","Friday","Monday","Tuesday","Wednesday","Thursday","Friday","Monday","Tuesday","Wednesday"]
price=[109.9499969,112.8000031,114.0500031,111.9000015,110.4499969,112.3499985,113,115.25,117.5500031,122.5,122.1999969,122,120.5500031,121.1500015,120.8499985,120.5999985,122.0999985,121.8000031,120,124]
close=np.array(price)
volum=[48824400,25681200,13950300,10554000,7675400,8613400,8795700,16049700,16903900,19869100,15273700,14988100,4513100,5775500,5888400,4007500,5424900,2245500,3489800,2965400
]
volume=np.array(volum)
weekdays=["Monday","Tuesday","Wednesday","Thursday","Friday"]
day2num=[]
for day in days:
    if day=="Monday":
        day2num.append(0)
    elif day=="Tuesday":
        day2num.append(1)
    elif day=="Wednesday":
        day2num.append(2)
    elif day=="Thursday":
        day2num.append(3)
    elif day=="Friday":
        day2num.append(4)
day_in_num=np.array(day2num)
day_in_num


array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2])

In [2]:
days_avg=[]
for i in range(5):
    indices=np.where(day_in_num==i)
    prices=np.take(close,indices)
    avg=np.mean(prices)
    print("Day:",i,"\nprices:",prices,"\naverag",avg)
    days_avg.append(avg)
days_avg=np.array(days_avg) #converting the python array to numpy for applying functions
days_avg

Day: 0 
prices: [[ 114.0500031  115.25       120.5500031  121.8000031]] 
averag 117.912502325
Day: 1 
prices: [[ 111.9000015  117.5500031  121.1500015  120.       ]] 
averag 117.650001525
Day: 2 
prices: [[ 110.4499969  122.5        120.8499985  124.       ]] 
averag 119.44999885
Day: 3 
prices: [[ 109.9499969  112.3499985  122.1999969  120.5999985]] 
averag 116.2749977
Day: 4 
prices: [[ 112.8000031  113.         122.         122.0999985]] 
averag 117.4750004


array([ 117.91250232,  117.65000152,  119.44999885,  116.2749977 ,
        117.4750004 ])

In [3]:
np.take(weekdays,np.argmax(days_avg)) #will return the day with the highest avg price

'Wednesday'

In [4]:
returns=np.diff(np.log(close))
print(returns)

positive_return=np.where(returns>0)
print(positive_return)

good_days=np.take(days,positive_return)
print(good_days)

[ 0.02559068  0.01102061 -0.01903135 -0.01304273  0.01705608  0.00576883
  0.01971586  0.01976012  0.04124723 -0.00245201 -0.00163798 -0.01195641
  0.00496483 -0.00247936 -0.00207082  0.0123611  -0.00245999 -0.01488864
  0.03278982]
(array([ 0,  1,  4,  5,  6,  7,  8, 12, 15, 18], dtype=int64),)
[['Thursday' 'Friday' 'Wednesday' 'Thursday' 'Friday' 'Monday' 'Tuesday'
  'Monday' 'Thursday' 'Tuesday']]


In [87]:
max_vol=np.argmax(volume)

print(np.take(volume,max_vol)) #highest volume eversold

print(np.take(days,max_vol)) #this tells us when was the highest volume

NameError: name 'volume' is not defined

kjdfkj

In [5]:
import numpy as np
dates, price, close=np.loadtxt('prices.csv', delimiter=',', usecols=(0,2,3), unpack=True, dtype='str')
#print(type(dates))
#print(type(price))

In [5]:
i=0
str_date=[]
str_close=[]
str_price=[]
for date in dates:
    zz=date.split("'")
    str_date.append(zz[1])
for cl in close:
    clz=cl.split("'")
    str_close.append(clz[1])
for pr in price:
    prz=pr.split("'")
    str_close.append(prz[1])
#print(type(str_close[1]))   


In [4]:
import datetime
def dates2num(s):
    return datetime.datetime.strptime(s, "%d-%m-%Y").date().weekday()
dates=list(map(dates2num,str_date))
dates=np.asanyarray(dates,'f')
price=np.asanyarray(str_price,'f')
close=np.asanyarray(str_close,'f')

In [41]:
avgs=np.zeros(5)
for i in range(5):
    indices = np.where(dates == i)
    prices = np.take(close, indices)
    avg = np.mean(prices)
    print("Day", i, "\nprices", prices, "\nAverage", avg)
    avgs[i] = avg
    
print(avgs)
    
    
    

Day 0 
prices [[ 214.00999451  210.11000061  203.07000732  194.72999573  194.11999512
   200.41999817  208.99000549  219.07998657  223.83999634  224.75
   232.38999939  238.49000549  242.29000854  247.07000732  269.5
   266.3500061   253.99000549  254.22000122  246.75999451  250.94000244
   254.27999878  270.17001343  268.29998779  257.29000854  245.58001709
   259.27999878  261.8500061   261.75        247.63999939  245.79998779
   242.5         267.04000854  283.23001099  291.15997314  278.63998413
   295.36001587  318.          308.83999634  304.17999268  318.61999512
   307.04000854  313.35998535  316.86999512  320.1499939   321.67001343
   322.20999146  324.68002319  329.57000732  342.45001221  337.44998169
   339.32000732  351.88000488  359.17999268  353.21002197  355.35998535
   353.55999756  339.29998779  350.44000244  341.19000244  330.79998779
   331.8500061   353.01000977  346.27999878  347.6000061   333.29998779
   334.3999939   338.03997803  326.6000061   315.32000732  332.

In [7]:
zzz=np.zeros(5)
zzz[2]=4
zzz

array([ 0.,  0.,  4.,  0.,  0.])

In [8]:
np.argmax(avgs)

NameError: name 'avgs' is not defined

In [63]:
returns=np.diff(close)/close[:-1]
slicing_returns=returns[:1000]
positive_indexes=np.where(slicing_returns>0) #index of days with positive returns

days_poitiv=np.take(dates,positive_indexes)
days_poitiv=days_poitiv.tolist()#converting the numpy array to list
"""the length of the days_positiv was 1 therefore we did the below step"""
days_poitiv=[lii for li in days_poitiv for lii in li]
print(len(days_poitiv))


528


In [98]:
#checking the day with most posetive return

num_of_days={0:0,1:0,2:0,3:0,4:0}
#for key,val in num_of_days.items:
for datss in days_poitiv:
    if datss in num_of_days:
        num_of_days[datss]+=1
print(num_of_days)


{0: 101, 1: 105, 2: 96, 3: 94, 4: 132}


In [99]:
high=0
for key,val in num_of_days.items():
    if high<val:
        high=val


132
